import type { ComponentType } from 'react';
import {
  ButtonVariantsDemo,
  ButtonSizesDemo,
  ButtonStatesDemo,
  ButtonUsageGoodDemo,
  ButtonUsageBadDemo,
  ButtonColorGoodDemo,
  ButtonColorBadDemo,
} from './button-demos';
import {
  InputStatesDemo,
  InputUsageGoodDemo,
  InputUsageBadDemo,
  SelectStatesDemo,
  SelectUsageGoodDemo,
  SelectUsageBadDemo,
  FormFieldStatesDemo,
  FormFieldUsageGoodDemo,
  FormFieldUsageBadDemo,
} from './form-demos';
import {
  CardAnatomyDemo,
  CardUsageGoodDemo,
  CardUsageBadDemo,
  BadgeVariantsDemo,
  BadgeUsageGoodDemo,
  BadgeUsageBadDemo,
  SpinnerPlacementDemo,
  SpinnerUsageGoodDemo,
  SpinnerUsageBadDemo,
} from './atom-demos';
import {
  AlertDialogAnatomyDemo,
  AlertDialogLiveDemo,
  AlertDialogUsageGoodDemo,
  AlertDialogUsageBadDemo,
  OverlayDialogAnatomyDemo,
  OverlayDialogLiveDemo,
  OverlayDialogUsageGoodDemo,
  OverlayDialogUsageBadDemo,
} from './overlay-demos';
import {
  PageTitleLiveDemo,
  PageTitleUsageBadDemo,
  FilterBarLiveDemo,
  FilterBarUsageBadDemo,
  ToolbarPatternDemo,
  ToolbarUsageGoodDemo,
  ToolbarUsageBadDemo,
  TabsPatternDemo,
  TabsUsageGoodDemo,
  TabsUsageBadDemo,
  SidebarLinkPatternDemo,
  SidebarLinkUsageGoodDemo,
  SidebarLinkUsageBadDemo,
} from './pattern-demos';
import {
  TableHeaderDemo,
  TableFooterDemo,
  TableUsageGoodDemo,
  TableUsageBadDemo,
} from './table-demos';
import {
  TableActionsSpacingDemo,
  TableActionsSpacingGoodDemo,
  TableActionsSpacingBadDemo,
} from './table-actions-spacing-demos';
import {
  StateTriptychDemo,
  StateUsageGoodDemo,
  StateUsageBadDemo,
  ColorTokensSwatchesDemo,
  ColorTokensUsageGoodDemo,
  ColorTokensUsageBadDemo,
  CrudAnatomyDemo,
  CrudUsageGoodDemo,
  CrudUsageBadDemo,
  TypographyHierarchyDemo,
  TypographyUsageGoodDemo,
  TypographyUsageBadDemo,
  IconSizeHierarchyDemo,
  IconOnlyVsTextDemo,
  IconUsageGoodDemo,
  IconUsageBadDemo,
  HoverBandDemo,
  HoverCursorDemo,
  HoverDownloadDemo,
  HoverUsageGoodDemo,
  HoverUsageBadDemo,
  FocusActiveDemo,
  FocusUsageGoodDemo,
  FocusUsageBadDemo,
  SearchHighlightUsageGoodDemo,
  SearchHighlightUsageBadDemo,
} from './ui-common-demos';

/**
 * 実描画見本の registry（mdl-0011）。content/*.ts（純データ）は demo キーだけを参照し、
 * JSX 実体はここへ集約する（content 側に JSX を持ち込まない）。
 * キーが content から参照されているのに未登録だと manifest.test が fail する。
 */
export const DEMOS: Record<string, ComponentType | undefined> = {
  'button-variants': ButtonVariantsDemo,
  'button-sizes': ButtonSizesDemo,
  'button-states': ButtonStatesDemo,
  'button-usage-good': ButtonUsageGoodDemo,
  'button-usage-bad': ButtonUsageBadDemo,
  'button-color-good': ButtonColorGoodDemo,
  'button-color-bad': ButtonColorBadDemo,
  'input-states': InputStatesDemo,
  'input-usage-good': InputUsageGoodDemo,
  'input-usage-bad': InputUsageBadDemo,
  'select-states': SelectStatesDemo,
  'select-usage-good': SelectUsageGoodDemo,
  'select-usage-bad': SelectUsageBadDemo,
  'form-field-states': FormFieldStatesDemo,
  'form-field-usage-good': FormFieldUsageGoodDemo,
  'form-field-usage-bad': FormFieldUsageBadDemo,
  'card-anatomy': CardAnatomyDemo,
  'card-usage-good': CardUsageGoodDemo,
  'card-usage-bad': CardUsageBadDemo,
  'badge-variants': BadgeVariantsDemo,
  'badge-usage-good': BadgeUsageGoodDemo,
  'badge-usage-bad': BadgeUsageBadDemo,
  'spinner-placement': SpinnerPlacementDemo,
  'spinner-usage-good': SpinnerUsageGoodDemo,
  'spinner-usage-bad': SpinnerUsageBadDemo,
  'alert-dialog-anatomy': AlertDialogAnatomyDemo,
  'alert-dialog-live': AlertDialogLiveDemo,
  'alert-dialog-usage-good': AlertDialogUsageGoodDemo,
  'alert-dialog-usage-bad': AlertDialogUsageBadDemo,
  'overlay-dialog-anatomy': OverlayDialogAnatomyDemo,
  'overlay-dialog-live': OverlayDialogLiveDemo,
  'overlay-dialog-usage-good': OverlayDialogUsageGoodDemo,
  'overlay-dialog-usage-bad': OverlayDialogUsageBadDemo,
  'page-title-live': PageTitleLiveDemo,
  'page-title-usage-bad': PageTitleUsageBadDemo,
  'filter-bar-live': FilterBarLiveDemo,
  'filter-bar-usage-bad': FilterBarUsageBadDemo,
  'toolbar-pattern': ToolbarPatternDemo,
  'toolbar-usage-good': ToolbarUsageGoodDemo,
  'toolbar-usage-bad': ToolbarUsageBadDemo,
  'tabs-pattern': TabsPatternDemo,
  'tabs-usage-good': TabsUsageGoodDemo,
  'tabs-usage-bad': TabsUsageBadDemo,
  'sidebar-link-pattern': SidebarLinkPatternDemo,
  'sidebar-link-usage-good': SidebarLinkUsageGoodDemo,
  'sidebar-link-usage-bad': SidebarLinkUsageBadDemo,
  'state-triptych': StateTriptychDemo,
  'state-usage-good': StateUsageGoodDemo,
  'state-usage-bad': StateUsageBadDemo,
  'color-tokens-swatches': ColorTokensSwatchesDemo,
  'color-tokens-usage-good': ColorTokensUsageGoodDemo,
  'color-tokens-usage-bad': ColorTokensUsageBadDemo,
  'crud-anatomy': CrudAnatomyDemo,
  'crud-usage-good': CrudUsageGoodDemo,
  'crud-usage-bad': CrudUsageBadDemo,
  'typography-hierarchy': TypographyHierarchyDemo,
  'typography-usage-good': TypographyUsageGoodDemo,
  'typography-usage-bad': TypographyUsageBadDemo,
  'icon-size-hierarchy': IconSizeHierarchyDemo,
  'icon-only-vs-text': IconOnlyVsTextDemo,
  'icon-usage-good': IconUsageGoodDemo,
  'icon-usage-bad': IconUsageBadDemo,
  'hover-band': HoverBandDemo,
  'hover-cursor': HoverCursorDemo,
  'hover-download': HoverDownloadDemo,
  'hover-usage-good': HoverUsageGoodDemo,
  'hover-usage-bad': HoverUsageBadDemo,
  'focus-active-demo': FocusActiveDemo,
  'focus-usage-good': FocusUsageGoodDemo,
  'focus-usage-bad': FocusUsageBadDemo,
  'search-highlight-usage-good': SearchHighlightUsageGoodDemo,
  'search-highlight-usage-bad': SearchHighlightUsageBadDemo,
  'table-header': TableHeaderDemo,
  'table-footer': TableFooterDemo,
  'table-usage-good': TableUsageGoodDemo,
  'table-usage-bad': TableUsageBadDemo,
  'table-actions-spacing': TableActionsSpacingDemo,
  'table-actions-spacing-good': TableActionsSpacingGoodDemo,
  'table-actions-spacing-bad': TableActionsSpacingBadDemo,
};
